services:
  broker:
    build:
      context: ./Broker
      dockerfile: Dockerfile
    container_name: broker
    env_file:
      - ./Broker/.env
    restart: unless-stopped
    environment:
      NODE_ENV: production
    command: >
      bash -c "npm run start"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.broker.rule=Host(`broker.luchsnode.com`)
      - traefik.http.routers.broker.entrypoints=websecure
      - traefik.http.routers.broker.tls=true
      - traefik.http.routers.broker.tls.certresolver=letsencrypt
      - traefik.http.services.broker.loadbalancer.server.port=5022
  client-gateway:
    build: ./client-gateway
    container_name: client_gateway
    restart: unless-stopped
    environment:
      GRPC_PORT: 50051
    networks:
      - internal

networks:
  web:
    external: true