services:
  broker:
      build:
        context: ./Broker
        dockerfile: Dockerfile
      container_name: broker
      env_file:
        - ./Broker/.env
      restart: unless-stopped
      environment:
        NODE_ENV: production
      command: >
        bash -c "
        npm run start
        "
      ports:
        - "5022:5022"